CREATE TABLE TMS_EMPLOYEE
(
 EMPID int PRIMARY KEY,
 PROJECTID int,
 USERNAME varchar2(20) NOT NULL UNIQUE,
 FIRSTNAME varchar2(10) NOT NULL,
 LASTNAME  varchar2(10) NOT NULL,
 ROLE  varchar2(10) NOT NULL,
 COUNTRY  varchar2(20) NOT NULL,
 DOJ   DATE,
 PASSWORD varchar2(20) NOT NULL,
 EMAIL varchar2(50) NOT NULL,
 PHONENUMBER  varchar2(12) NOT NULL,
 CREATED_BY varchar2(20) NOT NULL,
 DATE_CREATED TIMESTAMP NOT NULL,
 LAST_UPDATED_BY varchar2(20) NOT NULL,
 LAST_UPDATE_DATE TIMESTAMP NOT NULL
)