CREATE TABLE TMS_TIMESHEET
(
 TIMESHEET_ID int PRIMARY KEY,
 PROJECTID int,
 EMPID  int,
 MANAGERID int,
 BEGIN_DATE DATE NOT NULL,
 END_DATE   DATE NOT NULL,
 DESCRIPTION varchar2(10) NOT NULL,
 SUNDAY_HRS	int,
 MONDAY_HRS  int,
 TUESDAY_HRS int,
 WEDNESDAY_HRS int,
 THURSDAY_HRS int,
 FRIDAY_HRS int,
 SATURDAY_HRS int,
 TOTALHOURS int,
 STATUS varchar2(20) NOT NULL,
 CREATED_BY varchar2(50) NOT NULL,
 DATE_CREATED TIMESTAMP NOT NULL,
 LAST_UPDATED_BY varchar2(50) NOT NULL,
 LAST_UPDATED_DATE TIMESTAMP NOT NULL,
 FOREIGN KEY (PROJECTID) REFERENCES TMS_PROJECT(PROJECTID),
 FOREIGN KEY (EMPID ) REFERENCES TMS_EMPLOYEE(EMPID)
 )


